# Generated by Django 4.1.3 on 2022-11-09 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "user_id",
                    models.CharField(max_length=200, primary_key=True, serialize=False),
                ),
                ("user_email", models.EmailField(max_length=254)),
                ("user_pw", models.TextField()),
                ("user_name", models.CharField(max_length=30)),
                (
                    "user_validation",
                    models.CharField(
                        choices=[
                            ("General", "Lv1"),
                            ("Employee", "Lv2"),
                            ("Manager", "Lv3"),
                            ("Admin", "Lv4"),
                        ],
                        default="General",
                        max_length=10,
                    ),
                ),
                ("user_create_time", models.DateTimeField(auto_now_add=True)),
                ("user_updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
