# Generated by Django 2.2.1 on 2022-10-31 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='user_pwd',
            new_name='user_pw',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='user_level',
            new_name='user_validation',
        ),
    ]
