# Generated by Django 4.1.3 on 2022-11-09 21:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("signup", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Document",
            fields=[
                ("file_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("file_path", models.FileField(upload_to="upload_files/%Y%m%d/")),
                ("file_name", models.CharField(max_length=200)),
                ("file_create_time", models.DateTimeField(auto_now_add=True)),
                ("file_updated_at", models.DateTimeField(auto_now=True)),
                (
                    "file_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="signup.user"
                    ),
                ),
            ],
        ),
    ]
